// @refresh reset

import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./(componenets)/navbar/navbar";
import Headers from "./(componenets)/headers/headers";
import Footer from "./(componenets)/footer/footer";
export const metadata: Metadata = {
   title: "Spero",
   description: "Generated by create next app",
 };

export default function Layout({ children }: { children: React.ReactNode }) {
  
  return (
    <html >
       <Headers />  
      <body  data-mobile-nav-style="full-screen-menu" data-mobile-nav-bg-color="#353642" className="custom-cursor overflow-x-hidden" >
      <Navbar/>
        {children}
         <Footer/> 
      </body>
      </html>
  );
  
}
